### ISSUE TITLE
Inconsistent success

### ISSUE THREAD

**Issue by gioypi** [mateimarica/old-genius#2]
I like this approach that does not need to reload the page each time, but, unfortunately, it does not always work. I didn't find any patterns when it doesn't. Closing and reopening Firefox might be enough to make it not work, unless turned off and on again.

**Comment by Gameskiller01** [comment]
I've found that when opening a genius page it'll always open as the new song page, then if I toggle the extension off and on again it'll reload it as the old page. Then if I immediately select another song page it'll load as the old page just fine, but if I stay on the same song page for a few minutes and then select another song page it'll load as the new page.

**Comment by mateimarica** [comment]
Haha that's pretty odd. I'll look into this.

**Comment by mateimarica** [comment]
Haha that's pretty odd. I'll look into this.
@Gameskiller01 are you on Chrome or Firefox?

**Comment by Gameskiller01** [comment]
Firefox 112.0.2, Windows 11 Pro 22621.1702, Old Genius 1.0.5

**Comment by mateimarica** [comment]
Just pushed an update, should be fixed. Apologies for the delay.
